### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by bcg62** [Arno0x/TwoFactorAuth#8]
using nginx and getting this after filling out the install page, maybe i'm missing something?

Warning: SQLite3::exec(): no such table: USERS in /usr/local/www/portal/twofactorauth/install/install.php on line 76

Fatal error: Call to undefined function hash() in /usr/local/www/portal/twofactorauth/lib/dbManager.php on line 32

**Comment by bcg62** [comment]
I see, I'm missing php55-hash. may want to include this a dep in the readme.

**Comment by Arno0x** [comment]
Ok, thanks for the heads-up. I'll update the readme, though I don't remember having to installed this lib (might be installed by default on my systems...)

**Comment by bcg62** [comment]
It's all of these on freebsd

php55-sqlite3
php55-gd
php55-hash
php55-openssl
php55-zlib
php55-session
